### ISSUE TITLE
How to make a paletted bitmap

### ISSUE THREAD

**Issue by henry42** [squix78/minigrafx#12]
How to make a paletted bitmap?
and why "return" in line 783 of MiniGrafx.cpp causing the drawBmpFromPgm function can not be used?
Thanks!

**Comment by lorol** [comment]
Try [this](http://web.295.ca/295forums/phpBB2/display.htm) (live)
The source and details are [here](https://github.com/lorol/esp8266-weather-station-color/tree/master/resources/converter-tool)
