### ISSUE TITLE
CS line not being pulled low (EPD 2.9)

### ISSUE THREAD

**Issue by mattncsu** [squix78/minigrafx#15]
I'm using the EPD_Waveshare_2_9.ino example sketch and defined my pins as 
```
#define CS 0 
#define RST 15  
#define DC 2  
#define BUSY 16 
```
I'm using I2C so I couldn't use pins 4&5.  Here is what I see on the logic analyzer:
![image](https://user-images.githubusercontent.com/24309552/35180243-71f5929a-fd7a-11e7-9da7-d0fd49be3ddf.png)
If I unplug CS, it drops low, and the screen updates as expected in the example sketch.
I'm using a Huzzah Feather, per the [pinout](https://learn.adafruit.com/adafruit-feather-huzzah-esp8266/pinouts), it does not have an internal pullup.

Do I need to change any other definitions to use alternate pins?

**Comment by G6EJD** [comment]
Have you tried a different pin for CS ? I use gpio15 without any problems, Also, note on nearly all boards GPIO-0 has to be pulled high to ensure the ESP enters the correct boot mode, usually with a 10K resistor. The Huzzah has a pull-up on GPIO-0 as expected.

You can redefine the I2C pins provided they are not set by one of the libraries. Wire.begin(SDApin,SCLpin); Maybe rearrange your circuit.

Have you tried under programme control setting GPIO-0 low in a short no-frills simple programme that sets the pin low?

From the Huzzah notes: 

'GPIO #0, which does not have an internal pullup, and is also connected to both a mini tactile switch and red LED. This pin is used by the ESP8266 to determine when to boot into the bootloader. If the pin is held low during power-up it will start bootloading! That said, you can always use it as an output, and blink the red LED.'

So does the RED led blink when the screen is being updated (i.e. CS is active)?
