### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by mattncsu** [squix78/minigrafx#17]
Can you update minigrafx to support ESP32?  When I try to compile for ESP32, I get:

> C:\Users\Matt\Documents\Arduino\libraries\minigrafx-master\src\MiniGrafx.cpp:934:15: error: 'SPIFFS' was not declared in this scope
>    File file = SPIFFS.open(fileName, "r");

**Comment by G6EJD** [comment]
32 #if defined(ESP32) 
33   #include <SPIFFS.h> 
34 #endif 

So it does include SPIFFS when using the ESP32
