### ISSUE TITLE
ESP32 hwSPI = false will be cause panic

### ISSUE THREAD

**Issue by vslinuxdotnet** [squix78/minigrafx#19]
Hello,
I found that in device ESP32 the function:
ILI9341_SPI::ILI9341_SPI(int8_t cs, int8_t dc, int8_t mosi,
           int8_t sclk, int8_t rst, int8_t miso) : DisplayDriver(ILI9341_TFTWIDTH, ILI9341_TFTHEIGHT) {

The var "hwSPI = false" will cause kernel guru panic in SPI init.
In ESP8266 works in both SPI modes hwSPI true or false.
Please analise it. 
Thank you.

**Comment by armedia-rudy** [comment]
Hi, 
I'd like to do some animation on the TFT screen, so I am very interested in your frame buffering solution.

I am also having issues running your examples on an ESP32. While trying to run your BasicDrawing example, I got the error, "Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled." I'm using an ILI9341 TFT on the HSPI pins, so I init'd with:

ILI9341_SPI tft = ILI9341_SPI(TFT_CS, TFT_DC,13,14,4,12);

I got these results from decoding the backtrace with the ESP Exception Decoder tool:

`0x400d2f98: spiWriteNL at \Arduino15\packages\esp32\hardware\esp32\1.0.0\cores\esp32\esp32-hal-spi.c line 861`
`0x400d0f3e: SPIClass::writeBytes(unsigned char*, unsigned int) at \Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\SPI\src\SPI.cpp line 213`
`0x400d15dd: ILI9341_SPI::writeBuffer(unsigned char*, unsigned char, unsigned short*, unsigned short, unsigned short, unsigned short, unsigned short) at \Arduino\libraries\minigrafx-master\src\ILI9341_SPI.cpp line 436`
`0x400e9b19: MiniGrafx::commit(unsigned short, unsigned short) at \Arduino\libraries\minigrafx-master\src\MiniGrafx.cpp line 573`
`0x400d0bb7: setup() at \Temp\arduino_modified_sketch_316460/BasicDrawing.ino line 76`
`0x400e8c37: loopTask(void*) at \Arduino15\packages\esp32\hardware\esp32\1.0.0\cores\esp32\main.cpp line 15`

I've successfully run the Adafruit IL9341 library with this setup, so I've confirmed the wiring is correct. However, when I run your example, the screen just flashes between a white background and grey/black stripes. Can you offer any insight? 

Thanks
