### ISSUE TITLE
Carosel example needs gfx.commit();

### ISSUE THREAD

**Issue by tikitunes** [squix78/minigrafx#25]
The II9341 carosel example sketch from the MiniGrafx Library shows nothing as-is.  

Adding  gfx.commit(); as the last line of loop() enables the frames to be displayed and the carosel demo will show something.

However, the demo still has problems even after adding the gfx.commit(). There might be multiple issues, but the most important is frame switching does not clean up the previous frames content.  After very little time the frames produce a garbled mess on the screen with overwritten text.

I have a favor, please.  HOW can I change the behavior of the frame transition (make it replace content en-mass rather than the animated slider).  The animation looks neat when it's look-alike weather forecast, but I have an application in mind that will show disparate content, and the slider animation might be a jarring transition between content.

**Comment by ghost** [comment]
High tikitunes,
in the loop you filled in first gfx.fillBuffer(0);
in the end of the loop you filled in gfx.commit();

then works ;-)
