### ISSUE TITLE
How do you make a display invert?

### ISSUE THREAD

**Issue by pierpe83** [squix78/minigrafx#30]
Is the invert function available in this library?
If so, how do you call it in the code?

**Comment by mattncsu** [comment]
`colorSwap(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t color1, uint16_t color2)`

Give it a rectangle and the colors to swap. For example, in my code I invert the top 20 pixels of the display (from black on white to white on black) like this:
`gfx.colorSwap(0,0,gfx.getWidth(),20,0,1);`
