### ISSUE TITLE
WaveShare : is in the roadmap the capability to draw in red  / yellow ?

### ISSUE THREAD

**Issue by r2d2r01** [squix78/minigrafx#33]
Hi Squix, how draw a pixel, line,... in color other that black/white (red/yellow)  ? Whan I change your code (LUT).. to make appears all result in red it's OK but it's all.
I think it's only a capability when drawing bitmap (buffer of byte) associated with LUT preloaded.... in examples I can see ...
Thank's for answer
Frederic

**Comment by r2d2r01** [comment]
In theory I implement 2 framebuffer to draw them perfect result
So thank's for your library

**Comment by r2d2r01** [comment]
exe

**Comment by slavik0329** [comment]
> In theory I implement 2 framebuffer to draw them perfect result
> So thank's for your library

Were you able to make this work? If so, how?
