### ISSUE TITLE
Spende :)

### ISSUE THREAD

**Issue by Donderda** [squix78/minigrafx#40]
Moin moin, ich wollte Dir gerne was in den Hut werfen für deine Minigfx Library. Ich habe die in meinem Masterprojekt genutzt für ein PaPiRus und einem ESP32 und wollte mich wenigstens ein bisschen mit meinen bescheidenen Mitteln erkenntlich zeigen. 

Leider funktioniert das via payPal.me nicht. Die behaupten, dass Du die Zahlungen nur von Deiner Webseite aus annähmest... Magst Du Dir das zu gegebener Zeit mal anschauen und mir Rückmeldung geben?

**Comment by marcelstoer** [comment]
Thank you so much. Not sure which address you tried. paypal.me/thingpulse should work.
