### ISSUE TITLE
EPD_WaveShare_154D67.cpp:370:44: error: variable-sized object 'lineBuffer' may not be initialized

### ISSUE THREAD

**Issue by pragmantic** [squix78/minigrafx#54]
I get:
EPD_WaveShare_154D67.cpp: In member function 'void EPD_WaveShare154D67::fillRam(uint8_t, uint8_t)':

...\libraries\minigrafx-master\src\EPD_WaveShare_154D67.cpp:370:44: error: variable-sized object 'lineBuffer' may not be initialized

**Comment by pragmantic** [comment]
fixed it:

uint8_t lineBuffer[bytesPerLine] ;

**Comment by marcelstoer** [comment]
If you replace

```cpp
uint8_t lineBuffer[bytesPerLine] = {value};
```

with 

```cpp
uint8_t lineBuffer[bytesPerLine];
```

you are changing behavior as the initialization of index 0 is missing. Did you add `lineBuffer[0] = value;` or similar to address this?
