### ISSUE TITLE
Idea / Need code help for minigrafx ; Sliders and knobs

### ISSUE THREAD

**Issue by OstertagM** [squix78/minigrafx#55]
Dear Daniel,
your library is great and I want to use  for my smart home to display things.
I want to show my battery power form my solar panel if current goes into or coming out. 
I have seen how to make slider and fill squares. But how can I make an knob (16 color knob)
like this: It should be got into positive and negative from a certain start point.
I think for you or the people here this is very easy. 
![grafik](https://user-images.githubusercontent.com/26908656/104025609-31275300-51c5-11eb-96fd-7f2bc514cb7d.png)

**Comment by lorol** [comment]
: (Joke) it is easy:  https://ej2.syncfusion.com/demos/#/material/circular-gauge/user-interaction.html   ($2500)   
Is this what you need?

**Comment by OstertagM** [comment]
No I need some code for the minigrafx lib how to build this type of knob here :-).
And it should be go from - value to + max value. Middle point of knob should when go to negative and positive.
F.e. from upper middle point to left side of arc negative value and right side to arc positive value.
