### ISSUE TITLE
Share the font generator code

### ISSUE THREAD

**Issue by sstojos** [squix78/minigrafx#9]
Would it be possible to share font generation code ? 

Amy help in getting fonts generated would be great (e..g how does it compare to Adafruit fonts, would it be easier to convert Adafruti GFX fonts etc) 

We would also be able to improve the code if required.

Thanks,
Srdjan

**Comment by sstojos** [comment]
Just to inform you. I've found Java app on some of your previous posts, downloaded and generated my fonts without any problems.
Thanks for creating such a neat library. If only we would have microcontrollers with more RAM to use a full potential of this library.
Cheers!!!

**Comment by mattncsu** [comment]
Do you mind linking to one of the posts?

**Comment by sstojos** [comment]
Can't find the post any more, but I believe code is here:
https://github.com/squix78/esp8266-oled-ssd1306-font-converter

Simple:
- download  this single java file,
https://github.com/squix78/esp8266-oled-ssd1306-font-converter/blob/master/src/main/java/ch/squix/esp8266/fontconverter/rest/FontConverterV3.java
- create project in your favorite Java IDE (NetBeans IDE standard will do)
- inside the code set the name of the font, size and start and end char (note last char will nto be exported so always use one more)  font must be installed on the system - works on both windows and ubuntu
- run app - header file will be printed to system output.
Enjoy !

**Comment by mattncsu** [comment]
Awesome thanks!

**Comment by lorol** [comment]
@stojanos , thank you for the hint!
[Here](https://github.com/lorol/esp8266-oled-ssd1306/blob/master/resources/glyphEditor.html) you can find a standalone HTML+JS "visual editor", originally made by [Reivaxy](https://github.com/reivaxy/esp8266-oled-ssd1306). I just added some stuff to it. This tool allows you load and see/edit the generated C code by a browser like Mozilla.
